default:
  golem_name: carolinaKernels
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: /Users/josbop/Documents/Duke/semester1/STA523/final_proj_carolina_kernels
